name: Deploy to Github Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Use recent Ruby version
          bundler-cache: true  # Caches gems automatically

      - name: Install dependencies
        run: bundle install --path vendor/bundle

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
